# baseurl: ""
permalink: "/:categories/:year-:month-:day/:title"
url: https://coderjosie.xyz
# paginate: 12
# paginate_path: "dev/page:num"
# Build settings
markdown: kramdown
languages: ["zh", "en"]
defaultLang: zh
#plugins:
#  - jekyll-multiple-languages-plugin
# exclude_from_localizations: ["js", "css", "images"]
# default_locale_in_subfolder: true
#sass
  #style:compressed