# Site settings
title: Average Jo
description: Average Jo's Blog
owner: Average Jo
first_published: 2017
email: averagejo@163.com
baseurl: ""
permalink: "/:categories/:month-:day-:year/:title"
url: "https://xniawang.github.io"
# paginate: 12
# paginate_path: "dev/page:num"
social:
  github:
# Gems
# gems: [jekyll-paginate]
# Build settings
markdown: kramdown
#sass
  #style:compressed